### ISSUE TITLE
Atualize to Quasar!

### ISSUE THREAD

**Issue by eroizen** [mancuniancol/script.yts2kd#1]
Good Morning,
First of all, I'd like to tell you that I love your addons for Kodi!
I'm writing now to ask if you can atualize "yts2kd" addon. I'm having trouble with the auto-scanning service. When I turn kodi on, the service from yts2kd sends me a message of error. But when I mannually do the scan it runs perfectly. And I would suggest you to add Quasar in the list of addons to play the .strm files.
Thank you so much!

**Comment by mancuniancol** [comment]
Actually, this script is deprecated. Please, use yts viewer and it has UI you will find as addon, not like program. 
https://github.com/mancuniancol/plugin.video.yts
